Register
DoctorDib/BikeTheft pull request #42
Opened 2020-11-05 14:13 UTC by Yakitrak

Adding FE register route and component using Formik and Material UI
Including Merge changes from User branch from @MidgetJake

2020-11-05 17:42 UTC, BenRGH commented on client/src/Common/Helpers/User.tsx
> +import {
space between third party imports and local

2020-11-05 17:44 UTC, BenRGH commented on client/src/Common/Helpers/User.tsx
> +    for (let index = 0; index < errorKeysLength; index++) {
Should use array.some() here instead on the object as an array, rather than a for loop

2020-11-05 17:46 UTC, BenRGH commented on client/src/Common/Helpers/User.tsx
> +        Auth.signIn(user.username, user.password).then((response) => {
.then and .catch should be on the same indentation level

2020-11-05 17:47 UTC, BenRGH commented on client/src/Common/Interfaces/users.tsx
> +import UserMethodEnum from '../Enums/UserMethodEnum';
Line space needed

2020-11-05 17:54 UTC, BenRGH commented on client/src/Components/RegisterForm/index.tsx
> +
No need for this linespace

2020-11-05 17:54 UTC, BenRGH commented on client/src/Components/RegisterForm/index.tsx
> +import style from './styles';
Need linespace between third and local

2020-11-05 17:54 UTC, BenRGH commented on client/src/Components/RegisterForm/index.tsx
> +const SCHEMA = new PasswordValidator()
Better name

2020-11-05 17:55 UTC, BenRGH commented on client/src/Components/RegisterForm/index.tsx
> +                onSubmit={(values, { setSubmitting }) => {
No anon funcs in props

2020-11-05 17:56 UTC, BenRGH commented on client/src/Components/RegisterForm/index.tsx
> +                    signUp(values).then((result) => {
.then and .catch need to be on same line indent

2020-11-05 17:56 UTC, BenRGH commented on client/src/Components/RegisterForm/index.tsx
> +                {({ submitForm, isSubmitting }) => (
Not 100% sure but I think this is another anon func issue since its in render

2020-11-05 17:59 UTC, BenRGH commented on client/src/Components/Routing/UserContext.tsx
> +    state: IState;
Interfaces shouldn't be defined inline

2020-11-05 18:00 UTC, BenRGH commented on client/src/Components/Routing/UserContext.tsx
> +const reducer = (state: IState, action: IReducerAction) => {
Probably best to define the state arg as Readonly<IState> to be safe, even though you're using a new copy anyway

2020-11-05 18:02 UTC, BenRGH commented on client/src/Pages/Register/index.tsx
> +import NavBarComponent from '../../Components/Header';
Linespace between 3rd party and local

2020-11-05 18:03 UTC, BenRGH commented on client/src/Pages/Register/index.tsx
> +
Shouldn't be linespace here

2020-11-05 18:05 UTC, BenRGH commented on client/src/Components/RegisterForm/index.tsx
> +                validate={(values) => {
No anon funcs in props

2020-11-05 18:06 UTC, BenRGH commented on client/src/Components/RegisterForm/index.tsx
> +const SCHEMA = new PasswordValidator()
Also this singe line for each thing is a bit messy, did prettier do it?

2020-11-05 18:07 UTC, BenRGH commented on client/src/Common/Interfaces/users.tsx
> +    nickname: string | undefined;
Could probably just use the ? here to be consistent

2020-11-05 18:08 UTC, BenRGH commented on client/src/Common/Interfaces/users.tsx
> +export interface IState {
These two state interfaces (or at least this IState) should stay in the user context file with the rest of the state

2020-11-05 18:09 UTC, BenRGH commented on client/src/Components/Routing/UserContext.tsx
> +const initialState = {
Type

2020-11-05 18:09 UTC, BenRGH commented on client/src/Components/Routing/UserContext.tsx
> +const reducer = (state: IState, action: IReducerAction) => {
Also needs return type

2020-11-05 18:10 UTC, BenRGH commented on client/src/Components/RegisterForm/index.tsx
> +const ModifiedTextfield = (props) => (
Return type

2020-11-05 18:10 UTC, BenRGH commented on client/src/Components/RegisterForm/index.tsx
> +const SCHEMA = new PasswordValidator()
Also needs type, unless the PasswordValidator package doesn't support ts/have types

2020-11-05 18:11 UTC, BenRGH commented on client/src/Components/RegisterForm/index.tsx
> +interface Values {
Needs more specific name

2020-11-05 18:11 UTC, BenRGH commented on client/src/Components/RegisterForm/index.tsx
> +interface Values {
And it's an interface so needs to start with I

2020-11-05 18:18 UTC, MidgetJake commented on client/src/Common/Helpers/User.tsx
> +    for (let index = 0; index < errorKeysLength; index++) {
Out of curiosity, why?

If you want the best performance, use something like:
```js
for (let i = 0, keys = Object.keys(errors); i < keys.length; i++) {
    ...
}
```

I'd be more worried about why there are now 2 `Object.keys()` calls. With one being called every single iteration

2020-11-05 18:24 UTC, BenRGH commented on client/src/Common/Helpers/User.tsx
> +    for (let index = 0; index < errorKeysLength; index++) {
I suggest the .some() since this whole for block is only doing what could be done on a single line. Also yea the use of Object.keys() twice is messy

2020-11-07 12:03 UTC, DoctorDib commented
@Yakitrak - Please resolve changes for your PR to be merged

2020-11-07 12:58 UTC, DoctorDib commented on client/src/Common/Helpers/User.tsx
> +    for (let index = 0; index < errorKeysLength; index++) {
ESLint was complaining about your old method @MidgetJake - this is one of many solutions to fix the errors, feel free to implement your own fixes, but make sure ESLint approves.

2020-11-07 13:00 UTC, DoctorDib commented
![image](https://user-images.githubusercontent.com/14931616/98441865-f9365d80-20f8-11eb-8d93-f019c3ec500f.png)
I approve of the use of input fields and I will be changing my form around your style, however the structure of it needs changing before we merge this... As seen in the image attached, it looks like it's only for mobile... as discussed on your Trello card https://trello.com/c/lDZVSgta/60-page-user-registration - please try to follow this style.

2020-11-07 13:13 UTC, DoctorDib requested changes
As discussed in a comment, please can you change the structure of the register page.

2020-11-07 13:13 UTC, DoctorDib commented on client/src/Components/RegisterForm/index.tsx
> +                        errors.password = 'Password requires between 8 to 100 characters with at least 1 lowercase and uppcase alphabet and 2 number and 1 special character';
Personally I am not a fan of an error message saying "between 8 to 100 characters" since you don't usually see the "to 100", but it is personal opinion, feel free to ignore if other disapprove

2020-11-07 13:13 UTC, DoctorDib commented on client/src/Pages/Register/index.tsx
> +            <section style={{ width: '100%' }}>
Personally I would avoid using in lint style if possible, which is a reminder that we should go through the code and remove any existing in style props.

2020-11-07 13:13 UTC, DoctorDib commented on client/src/Components/Routing/UserContext.tsx
> +    const { children } = props;
Prop to top 👍 
In other words, Ben pointed out that the best practice is having props at the top of the function.

2020-11-07 13:13 UTC, DoctorDib commented on client/src/Components/Routing/UserContext.tsx
> +const initialState = {
My be worth moving this into the "Defaults" file
/Common/Helpers/Defaults.tsx

2020-11-07 13:13 UTC, DoctorDib commented on client/src/Components/RegisterForm/index.tsx
> +                {({ submitForm, isSubmitting }) => (
Yeah, I have been working on Formik on my other branch, I recommend using the hook version called useFormik.
https://formik.org/docs/api/useFormik

useFormik will avoid using anon functions.

2020-11-07 13:13 UTC, DoctorDib commented on client/src/Components/RegisterForm/index.tsx
> +                initialValues={{
As stated in another comment if you have this in /Common/Helpers/Defualts.tsx" you can avoid using 6-7 lines.

2020-11-07 13:17 UTC, BenRGH commented on client/src/Components/RegisterForm/index.tsx
> +                        errors.password = 'Password requires between 8 to 100 characters with at least 1 lowercase and uppcase alphabet and 2 number and 1 special character';
Yea normally it'd just say 'At least 8' and then show an error if it's too long

2020-11-07 13:18 UTC, BenRGH commented on client/src/Components/Routing/UserContext.tsx
> +const initialState = {
This is the one case where I'd disagree, initial state is normally kept with the state since its not a default so much as it is the starting point for state

2020-11-07 14:09 UTC, DoctorDib commented on client/src/Components/Routing/UserContext.tsx
> +const initialState = {
Fair enough, some of our code use the method I suggested :s

2020-11-07 15:34 UTC, BenRGH commented on client/src/Components/Routing/UserContext.tsx
> +const initialState = {
Yea normally its better to keep the defaults in one place like we have

2020-11-07 16:31 UTC, DoctorDib commented on client/src/Components/Routing/UserContext.tsx
> +const initialState = {
Not if you want to use that default in multiple locations, and by that point, may as well keep it all consistent

2020-11-11 21:48 UTC, DoctorDib commented
@Yakitrak - Can we get an ETA on this please, this is holding up @BenRGH branch.

2020-11-14 14:42 UTC, DoctorDib commented
@BenRGH - @Yakitrak  has pulled out of the project, I am going to go through this PR later and fix it up

2020-11-19 12:53 UTC, DoctorDib commented
Remaking on a new branch https://github.com/DoctorDib/BikeTheft/tree/new-register-page

2020-11-19 12:53 UTC, closed without merging